name = "LibriscraftAutumn2023"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2137ec4867212c4e352b48b61c3a39a59ad924dcc4696af6e4d75d0e5e5c2a5e"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
